# -*- coding: utf-8 -*-
"""Criando_Staging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HlnD7Uet7_ZZSKWK9K4roS40Fo5neYuZ
"""

import pandas as pd
import numpy as np
import os
import glob
import sqlite3
import gc

from google.colab import drive
drive.mount('/content/drive')

#!unzip /content/drive/MyDrive/Projeto_Final_BI/Mortalidade_Geral.zip -d /content/drive/MyDrive/Projeto_Final_BI/

URL = "/content/drive/MyDrive/Projeto_Final_BI/"

df_18 = pd.read_csv(URL+"Mortalidade_Geral_2018.csv", sep=";")

df_19 = pd.read_csv(URL+"Mortalidade_Geral_2019.csv", sep=";")

df_20 = pd.read_csv(URL+"Mortalidade_Geral_2020.csv", sep=";")

df_21 = pd.read_csv(URL+"Mortalidade_Geral_2021.csv", sep=";")

df_22 = pd.read_csv(URL+"Mortalidade_Geral_2022.csv", sep=";")

df_23 = pd.read_csv(URL+"Mortalidade_Geral_2023.csv", sep=";")
df_23 = df_23.rename(columns={'contador': 'CONTADOR'})

df_24 = pd.read_csv(URL+"Mortalidade_Geral_2024.csv", sep=";")
df_24 = df_24.rename(columns={'contador': 'CONTADOR'})

cols_18 = df_18.columns.values
cols_23 = df_23.columns.values
cols_24 = df_24.columns.values

set18 = set(cols_18)
set23 = set(cols_23)
set24 = set(cols_24)

colunas_18 = list(set18 - set24)
colunas_24 = list(set24 - set18)

to_drop = ["HORAOBITO", "CODMUNNATU", "ESC", "SERIESCFAL", "OCUP",
           "LOCOCOR", "CODESTAB", "ESTABDESCR", "IDADEMAE", "ESCMAE",
           "ESCMAE2010", "SERIESCMAE", "OCUPMAE", "QTDFILVIVO", "QTDFILMORT", "SEMAGESTAC", "CB_PRE",
           "DTATESTADO", "FONTE", "NUMEROLOTE", "DTINVESTIG", "CAUSABAS_O",
           "DTCADASTRO", "ATESTANTE", "STCODIFICA", "CODIFICADO", "VERSAOSIST",
           "VERSAOSCB", "FONTEINV", "DTRECEBIM", "ESCMAEAGR1", "ESCFALAGR1",
           "STDONOVA", "NUDIASOBCO", "NUDIASOBIN", "DTCADINV", "DTCONINV",
           "FONTES", "TPNIVELINV", "NUDIASINF", "DTCADINF", "DTCONCASO",
           "FONTESINF"]

lista_to_drop = to_drop + colunas_18 + colunas_24

lista_to_drop = list(set(lista_to_drop))

df_keys = {
    "2018" : df_18,
    "2019" : df_19,
    "2020" : df_20,
    "2021" : df_21,
    "2022" : df_22,
    "2023" : df_23,
    "2024" : df_24
}

for key in list(df_keys.keys()):
  df_keys[key].drop(columns=[c for c in df_keys[key].columns if c in lista_to_drop],
                      inplace=True)

conn = sqlite3.connect(URL+"staging.db")

for key in list(df_keys.keys()):
    df_keys[key].to_sql("STG_MORTALIDADE", conn, if_exists="append", index=False)
    print(f"Tabela mortalidade_{key} criada com sucesso! Com {len(df_keys[key])} registros.")
    del df_keys[key]
    gc.collect()

conn.commit()
conn.close()

conn = sqlite3.connect(URL+"staging.db")
cursor = conn.cursor()
cursor.execute("""
    ALTER TABLE STG_MORTALIDADE ADD COLUMN SK_MORTE INTEGER;
""")

cursor.execute(f"""
    UPDATE STG_MORTALIDADE
    SET SK_MORTE = rowid
    WHERE SK_MORTE IS NULL;
""")

conn.commit()
conn.close()

conn = sqlite3.connect(URL+"staging.db")

df_cid = pd.read_csv(URL+"CID_10.csv", sep=";")
df_cid.to_sql("cid", conn, if_exists="replace", index=False)

df_obitos_0_4 = pd.read_csv(URL+"Obitos_Evitaveis_0_a_4.csv", sep=";")
df_obitos_5_74 = pd.read_csv(URL+"Obitos_Evitaveis_5_a_74.csv", sep=";")

df_obitos_0_4.to_sql("obitos_evitaveis_infantil", conn, if_exists="replace", index=False)
df_obitos_5_74.to_sql("obitos_evitaveis_adulto", conn, if_exists="replace", index=False)

conn.commit()
conn.close()