# -*- coding: utf-8 -*-
"""DWCD_ESTCIV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zDNpG_TOD7koqLaxDgbLZtmb0Jm_3W_M
"""

import pandas as pd
import sqlite3
from datetime import datetime

URL = "/content/drive/MyDrive/Projeto_Final_BI/"

conn = sqlite3.connect(URL+"dw_mortalidade.db")

cur = conn.cursor()

dict_estciv = {
    -1 : "Não identificado",
    1 : "Solteiro",
    2 : "Casado",
    3 : "Viúvo",
    4 : "Separado",
    5 : "União Estável",
    9 : "Ignorado"
}

sks = len(dict_estciv.items())
df = pd.DataFrame(range(0, sks), columns=["SK_ESTCIV"])

df.loc[df["SK_ESTCIV"] == 0, "SK_ESTCIV"] = -1

df["CD_ESTCIV"] = dict_estciv.keys()
df["DS_ESTCIV"] = dict_estciv.values()

df["DT_CARGA"] = datetime.now().date()
df["DT_CARGA"].dtype

cur.execute("""

DROP TABLE IF EXISTS DWCD_ESTCIV;

""")

cur.execute("""
CREATE TABLE DWCD_ESTCIV (
    SK_ESTCIV INTEGER PRIMARY KEY,
    CD_ESTCIV INTEGER NOT NULL,
    DS_ESTCIV TEXT,
    DT_CARGA DATE
    );
""")

df.to_sql("DWCD_ESTCIV", conn, if_exists="append", index=False)

conn.commit()

conn.close()

