# -*- coding: utf-8 -*-
"""DWCD_CAUSAOBITO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W4kGGs2iSjurYo80NTXMBhHyXdmnKyV_

# Imports
"""

import pandas as pd
import sqlite3
from datetime import datetime
import numpy as np

"""# Connections"""

URL = "/content/drive/MyDrive/Projeto_Final_BI/"

conn_dw = sqlite3.connect(URL+"dw_mortalidade.db")
conn_stg = sqlite3.connect(URL+"staging.db")

cur_dw = conn_dw.cursor()
cur_stg = conn_stg.cursor()

"""# Functions"""

def treat_age(age: int):
  if age < 400:
    return 0
  if age >= 500:
    return 100 + age%100
  else:
    return age%100

def doenca_evitavel(df):
  conditions = [
    (df["IDADE"] < 5) & (df["IN_DE_CRIANCA"] == True),
    (df["IDADE"] >= 5) & (df["IN_DE_ADULTO"] == True)
  ]

  choices = [1, 1]

  df["IN_DE"] = np.select(conditions, choices, default=0)
  return df

"""# Code"""



query_stg = "SELECT CAUSABAS, CIRCOBITO, IDADE, SK_MORTE FROM STG_MORTALIDADE"

df_stg = pd.read_sql_query(query_stg, conn_stg)

query_cid = "SELECT SK_CID, CD_CID, IN_DE_CRIANCA, IN_DE_ADULTO FROM DWCD_CID"

df_cid = pd.read_sql_query(query_cid, conn_dw)

query_co = "SELECT SK_CIRCOBITO, CD_CIRCOBITO FROM DWCD_CIRCOBITO"

df_co = pd.read_sql_query(query_co, conn_dw)

df_stg.fillna(-1, inplace=True)
df_stg["CIRCOBITO"] = df_stg["CIRCOBITO"].astype("int")

df_stg["IDADE"] = df_stg["IDADE"].apply(treat_age)

df_stg_cid = pd.merge(df_stg,  df_cid, left_on="CAUSABAS", right_on="CD_CID")

df_stg_cid = doenca_evitavel(df_stg_cid)

df_stg_cid = df_stg_cid[["CD_CID", "CIRCOBITO", "IN_DE", "SK_MORTE"]]

df_stg_cid_co = pd.merge(df_stg_cid,  df_co, left_on="CIRCOBITO", right_on="CD_CIRCOBITO")
df_stg_cid_co = df_stg_cid_co[["CD_CID", "SK_CIRCOBITO", "IN_DE", "SK_MORTE"]]

df_stg_cid_co["SK_CAUSAOBITO"] = range(1, len(df_stg_cid_co) + 1)

df_stg_cid_co = df_stg_cid_co[["SK_CAUSAOBITO", "SK_MORTE", "CD_CID", "SK_CIRCOBITO", "IN_DE"]]

df_stg_cid_co = df_stg_cid_co.rename(columns={
    "CD_CID" : "CD_CAUSABAS"
}
)

df_stg_cid_co["DT_CARGA"] = datetime.now().date()

df_stg_cid_co

cur_dw.execute("""

DROP TABLE IF EXISTS DWCD_CAUSAOBITO;

""")

cur_dw.execute("""
CREATE TABLE DWCD_CAUSAOBITO (
    SK_CAUSAOBITO INTEGER PRIMARY KEY,
    SK_MORTE INTEGER NOT NULL,
    CD_CAUSABAS INTEGER NOT NULL,
    SK_CIRCOBITO INTEGER,
    IN_DE BOOLEAN,
    DT_CARGA DATE
    );
""")

df_stg_cid_co.to_sql("DWCD_CAUSAOBITO", conn_dw, if_exists="append", index=False)

