# -*- coding: utf-8 -*-
"""DWCD_ASSISTMED.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ImEYgeuE8N7z-x2jsP-_BbaSIl59P3cz
"""

import pandas as pd
import sqlite3
from datetime import datetime

URL = "/content/drive/MyDrive/Projeto_Final_BI/"

conn = sqlite3.connect(URL+"dw_mortalidade.db")

cur = conn.cursor()

dict_assistmed = {
    1 : "Sim",
    2 : "Não",
    9 : "Ignorado"
}

sks = len(dict_assistmed.items())
df = pd.DataFrame(range(1, sks+1), columns=["SK_ASSISTMED"])

df["CD_ASSISTMED"] = dict_assistmed.keys()
df["DS_ASSISTMED"] = dict_assistmed.values()

df["DT_CARGA"] = datetime.now().date()

cur.execute("""

DROP TABLE IF EXISTS DWCD_ASSISTMED;

""")

cur.execute("""
CREATE TABLE DWCD_ASSISTMED (
    SK_ASSISTMED INTEGER PRIMARY KEY,
    CD_ASSISTMED INTEGER NOT NULL,
    DS_ASSISTMED TEXT,
    DT_CARGA DATE
    );
""")

df.to_sql("DWCD_ASSISTMED", conn, if_exists="append", index=False)

conn.commit()

conn.close()

