# -*- coding: utf-8 -*-
"""DWCD_SEXO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KrFrcGSBsx-I6Dv-vYA-t294h1ulmvWs
"""

import pandas as pd
import sqlite3
from datetime import datetime

URL = "/content/drive/MyDrive/Projeto_Final_BI/"

conn = sqlite3.connect(URL+"dw_mortalidade.db")

dict_sex = {
    0 : "Ignorado",
    2 : "Feminino",
    1 : "Masculino",
}

sks = len(dict_sex.items())
df = pd.DataFrame(range(1, sks+1), columns=["SK_SEXO"])

df["CD_SEXO"] = dict_sex.keys()
df["DS_SEXO"] = dict_sex.values()

df["DT_CARGA"] = datetime.now().date()

df.to_sql("DWCD_SEXO", conn, if_exists="replace", index=False)

conn.close()

