# -*- coding: utf-8 -*-
"""DWCD_GESTACIONAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/112oAGSaB56RpDwuQmpQXdoK6GcqU5-6f
"""

import pandas as pd
import sqlite3
from datetime import datetime

from google.colab import drive
drive.mount('/content/drive')

URL = "/content/drive/MyDrive/Projeto_Final_BI/"

conn = sqlite3.connect(URL+"dw_mortalidade.db")

cur = conn.cursor()

dict_gest = {
    -1 : "Não Identificado",
    1 : "Na Gravidez",
    2 : "No Parto",
    3 : "No Abortamento",
    4 : "42 Dias Após o Parto",
    5 : "De 43 Dias a 1 Ano Após o Parto",
    8 : "Não Ocorreu Nestes Períodos",
    9 : "Ignorado"
}

sks = len(dict_gest.items())

df = pd.DataFrame([-1] + list(range(1, sks)), columns=["SK_GESTACIONAL"])

df["CD_GESTACIONAL"] = dict_gest.keys()
df["DS_GESTACIONAL"] = dict_gest.values()

df["DT_CARGA"] = datetime.now().date()

cur.execute("""

DROP TABLE IF EXISTS DWCD_GESTACIONAL;

""")

cur.execute("""
CREATE TABLE DWCD_GESTACIONAL (
    SK_GESTACIONAL INTEGER PRIMARY KEY,
    CD_GESTACIONAL INTEGER NOT NULL,
    DS_GESTACIONAL TEXT NOT NULL,
    DT_CARGA DATE NOT NULL
    );
""")

df.to_sql("DWCD_GESTACIONAL", conn, if_exists="append", index=False)
conn.commit()
conn.close()