# -*- coding: utf-8 -*-
"""DWCD_CID10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YX-lQDbdLbjsrcTskIsRK4H3pLj8nXQ1
"""

import pandas as pd
import sqlite3
from datetime import datetime

URL = "/content/drive/MyDrive/Projeto_Final_BI/"

conn_extract = sqlite3.connect(URL+"staging.db")
conn_store = sqlite3.connect(URL+"dw_mortalidade.db")

cur = conn_store.cursor()

query = "SELECT * FROM STG_CID"
df_cid = pd.read_sql_query(query, conn_extract)

query = "SELECT * FROM STG_DE_CRIANCA"
df_crianca = pd.read_sql_query(query, conn_extract)

query = "SELECT * FROM STG_DE_ADULTO"
df_adulto = pd.read_sql_query(query, conn_extract)

df_cid.loc[df_cid["CD_CID"].isin(df_crianca["CD_CID"].unique()), "IN_DE_CRIANCA"] = 1
df_cid.loc[df_cid["CD_CID"].isin(df_adulto["CD_CID"].unique()), "IN_DE_ADULTO"] = 1
df_cid["IN_DE_CRIANCA"].fillna(0, inplace=True)
df_cid["IN_DE_ADULTO"].fillna(0, inplace=True)

df_cid["DT_CARGA"] = datetime.now().date()

df_cid["SK_CID"] = range(1, len(df_cid)+1)

df_cid = df_cid[['SK_CID', 'CD_CID', 'NM_CID', 'IN_DE_CRIANCA', 'IN_DE_ADULTO', 'DT_CARGA']]

cur.execute("""

DROP TABLE IF EXISTS DWCD_CID;

""")

cur.execute("""
CREATE TABLE DWCD_CID (
    SK_CID INTEGER PRIMARY KEY,
    CD_CID INTEGER NOT NULL,
    NM_CID TEXT,
    IN_DE_CRIANCA BOOLEAN,
    IN_DE_ADULTO BOOLEAN,
    DT_CARGA DATE
    );
""")

df_cid.to_sql("DWCD_CID", conn_store, if_exists="append", index=False)

conn_store.commit()

conn_extract.close()
conn_store.close()

