# -*- coding: utf-8 -*-
"""ETL_DWCD_UF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQuMMcqzP8UUdQB79XJrhXsi876TDl_B
"""

import pandas as pd
import numpy as np
from datetime import datetime
import sqlite3

URL = "/content/drive/MyDrive/Projeto_Final_BI/"

from google.colab import drive
drive.mount('/content/drive')

conn_extract = sqlite3.connect(URL+"staging.db")
cursor = conn_extract.cursor()
df_uf = pd.read_sql_query("SELECT CD_UF, SG_UF, NM_UF FROM STG_LOCALIDADE", conn_extract)
df_uf = df_uf.drop_duplicates().dropna()
conn_extract.close()

df_uf

df_uf.insert(0, 'SK_UF', range(1, len(df_uf) + 1))
df_uf['CD_UF'] = df_uf['CD_UF'].fillna(0).astype(int)
df_uf['DT_CARGA'] = datetime.now().date()

conn = sqlite3.connect(URL+"dw_mortalidade.db")
cur = conn.cursor()

cur.execute("""DROP TABLE IF EXISTS DWCD_UF;""")

cur.execute("""
CREATE TABLE IF NOT EXISTS DWCD_UF (
    SK_UF INTEGER PRIMARY KEY,
    CD_UF INTEGER NOT NULL,
    NM_UF TEXT,
    SG_UF TEXT,
    DT_CARGA DATE
);
""")

conn = sqlite3.connect(URL+"dw_mortalidade.db")
df_uf.to_sql('DWCD_UF', conn, if_exists='append', index=False)

conn.commit()
conn.close()