# -*- coding: utf-8 -*-
"""ETL UF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OK9zGQhcCy5YZqp-GGknpo5OMhqAb82R
"""

import pandas as pd
import numpy as np
from datetime import datetime
import sqlite3

URL = "/content/drive/MyDrive/Projeto_Final_BI/"

conn = sqlite3.connect(URL+"staging.db")
cursor = conn.cursor()
df_uf = pd.read_sql_query("SELECT CD_UF, NM_SIGLA_UF, NM_UF FROM STG_LOCALIDADE", conn)
df_uf = df_uf.drop_duplicates().dropna()
conn.close()
df_uf

df_uf.insert(0, 'SK_UF', range(1, len(df_uf) + 1))
df_uf['CD_UF'] = df_uf['CD_UF'].fillna(0).astype(int)
df_uf['DT_CARGA'] = datetime.now().date()
df_uf

con = sqlite3.connect(URL+"dw_mortalidade.db")
cur = con.cursor()

cur.execute("""
CREATE TABLE IF NOT EXISTS DWCD_UF (
    SK_UF INTEGER PRIMARY KEY,
    CD_UF INTEGER NOT NULL,
    NM_UF TEXT,
    NM_SIGLA_UF TEXT,
    DT_CARGA DATE
);
""")
con.commit()
con.close()

conn = sqlite3.connect(URL+"dw_mortalidade.db")
df_uf.to_sql('DWCD_UF', conn, if_exists='append', index=False)
conn.close()