# -*- coding: utf-8 -*-
"""ETL_CID_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1evZRW8EDAgRi9rIsI1ZA7Qsh8tGJbuTH

# Imports e URLs
"""

import requests
import pandas as pd
import sqlite3

url_cid = "https://cid10.cpp-ti.com.br/api"
URL = "/content/drive/MyDrive/Projeto_Final_BI/STG/"

"""# Composumindo API e Inserindo no Staging"""

response = requests.get(url_cid)

dados = response.json()

df = pd.json_normalize(dados['data'])

df = df[["codigo", "nome"]]

df.columns = ["CD_CID", "NM_CID"]
df['CD_CID'] = df['CD_CID'].str.replace('.', '')
df.to_csv("/content/drive/MyDrive/Projeto_Final_BI/CID_10.csv", index=False, encoding="utf-8")

conn = sqlite3.connect(URL+"staging.db")
df.to_sql('STG_CID', conn, if_exists='replace', index=False)
conn.close()