# -*- coding: utf-8 -*-
"""ETL_Localidades.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTCwbjA66MZOYgVmniRMrmXqtwNzqsuG

# Imports e URLs
"""

import requests
import pandas as pd
import sqlite3

url_ibge = "https://servicodados.ibge.gov.br/api/v1/localidades/municipios"
URL = "/content/drive/MyDrive/Projeto_Final_BI/STG/"

from google.colab import drive
drive.mount('/content/drive')

"""# Consumindo API e inserindo no Staging"""

resp = requests.get(url_ibge)
municipios = resp.json()

df = pd.json_normalize(municipios)

df = df[[
    "id",
    "nome",
    "microrregiao.nome",
    "microrregiao.mesorregiao.UF.id",
    "microrregiao.mesorregiao.UF.sigla",
    "microrregiao.mesorregiao.UF.nome"
]]

df.columns = ["CD_MUNICIPIO", "NM_MUNICIPIO", "NM_MICRORREGIAO", "CD_UF", "SG_UF", "NM_UF"]

df["CD_MUNICIPIO"] = df["CD_MUNICIPIO"].astype(str).str[:-1]

df.to_csv("/content/drive/MyDrive/Projeto_Final_BI/localidades.csv", index=False, encoding="utf-8")

conn = sqlite3.connect(URL+"staging.db")
df.to_sql('STG_LOCALIDADE', conn, if_exists='replace', index=False)
conn.commit()
conn.close()