# -*- coding: utf-8 -*-
"""ETL_Mortes_Evitaveis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gxMslWPw5Dn2cOczozaM8KkOdvV9FwNH

# Imports e URL
"""

import pandas as pd
import sqlite3

from google.colab import drive
drive.mount('/content/drive')

URL = "/content/drive/MyDrive/Projeto_Final_BI/STG/"

conn = sqlite3.connect(URL+"staging.db")

"""# Lendo CSVs e criando tabelas no Staging"""

df_obitos_0_4 = pd.read_csv(URL+"Obitos_Evitaveis_0_a_4.csv")
df_obitos_5_74 = pd.read_csv(URL+"Obitos_Evitaveis_5_a_74.csv")

df_obitos_0_4["Código CID-10"] = df_obitos_0_4["Código CID-10"].str.replace(".", "")
df_obitos_5_74["Código CID-10"] = df_obitos_5_74["Código CID-10"].str.replace(".", "")

df_obitos_0_4.columns = ['NM_DOENCA','CD_CID']
df_obitos_5_74.columns = ['NM_DOENCA','CD_CID']

df_obitos_0_4.to_sql("STG_DE_CRIANCA", conn, if_exists="replace", index=False)
df_obitos_5_74.to_sql("STG_DE_ADULTO", conn, if_exists="replace", index=False)

conn.close()