# -*- coding: utf-8 -*-
"""DIME_GESTACIONAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bRcxI7pFAcYpXsiIoCCCjhMWO9N874f9
"""

import sqlite3
import pandas as pd

URL = "/content/drive/MyDrive/Projeto_Final_BI/"
URL_STORE = URL+"DM/"

conn_extract = sqlite3.connect(URL+"dw_mortalidade.db")
conn_store = sqlite3.connect(URL_STORE+"dm_mortalidade.db")

cur_extract = conn_extract.cursor()
cur_store = conn_store.cursor()

query = "SELECT * FROM DWCD_GESTACIONAL"
df_gest = pd.read_sql_query(query, conn_extract)

df_gest.drop("DT_CARGA", inplace=True, axis=1)

conn_store.execute("""

DROP TABLE IF EXISTS DIME_GESTACIONAL;

""")

conn_store.execute("""
CREATE TABLE DIME_GESTACIONAL (
    SK_GESTACIONAL INTEGER PRIMARY KEY,
    CD_GESTACIONAL INTEGER NOT NULL,
    DS_GESTACIONAL TEXT
    );
""")

df_gest.to_sql("DIME_GESTACIONAL", conn_store, if_exists="append", index=False)

conn_extract.close()
conn_store.commit()
conn_store.close()

