# -*- coding: utf-8 -*-
"""DIME_CAUSAOBITO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DuByVb-VUeGmnvn5ap4Z4BNHD21byrI9
"""

import sqlite3
import pandas as pd

URL = "/content/drive/MyDrive/Projeto_Final_BI/"
URL_STORE = URL+"DM/"

conn_extract = sqlite3.connect(URL+"dw_mortalidade.db")
conn_store = sqlite3.connect(URL_STORE+"dm_mortalidade.db")

cur_extract = conn_extract.cursor()
cur_store = conn_store.cursor()

query ="""
  SELECT co.SK_CAUSAOBITO, cid.CD_CID, cid.NM_CID, co.IN_DE, cb.CD_CIRCOBITO, cb.DS_CIRCOBITO
  FROM DWCD_CAUSAOBITO co
  JOIN DWCD_CIRCOBITO cb
    ON co.SK_CIRCOBITO = cb.SK_CIRCOBITO
  JOIN DWCD_CID cid
    ON co.SK_CID = cid.SK_CID

"""

dime_cb = pd.read_sql_query(query, conn_extract)

conn_store.execute("""

DROP TABLE IF EXISTS DIME_CAUSAOBITO;

""")

conn_store.execute("""
CREATE TABLE DIME_CAUSAOBITO (
    SK_CAUSAOBITO INTEGER PRIMARY KEY,
    CD_CID INTEGER NOT NULL,
    NM_CID TEXT NOT NULL,
    IN_DE INTEGER NOT NULL,
    CD_CIRCOBITO INTEGER NOT NULL,
    DS_CIRCOBITO TEXT NOT NULL
    );
""")

dime_cb.to_sql("DIME_CAUSAOBITO", conn_store, if_exists="append", index=False)

conn_extract.close()
conn_store.commit()
conn_store.close()

