# -*- coding: utf-8 -*-
"""DIME PESSOA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dxNpd0jeoOtAM6IwbWMqM8w7uYambAZr

# Imports e conexões
"""

import sqlite3
import pandas as pd

URL = "/content/drive/MyDrive/Projeto_Final_BI/"
URL_STORE = URL+"DM/"

conn_dw = sqlite3.connect(URL+"DW/dw_mortalidade.db")
conn_dm = sqlite3.connect(URL_STORE+"dm_mortalidade.db")

cur_dm = conn_dm.cursor()

df_dime = pd.read_sql_query("SELECT * FROM DIME_PESSOA", conn_dm)
df_dime

"""# Extraindo dados do DW"""

query = """
  SELECT
    PE.SK_PESSOA,
    SX.CD_SEXO,
    SX.DS_SEXO,
    RC.CD_RACA,
    RC.DS_RACA,
    EC.CD_ESTCIV,
    EC.DS_ESTCIV,
    EL.CD_ESCOLARIDADE,
    EL.DS_ESCOLARIDADE,
    PE.IDADE,
    PE.FAIXA_ETARIA
  FROM DWCD_PESSOA AS PE
  JOIN DWCD_SEXO AS SX
    ON PE.SK_SEXO = SX.SK_SEXO
  JOIN DWCD_RACA AS RC
    ON PE.SK_RACA = RC.SK_RACA
  JOIN DWCD_ESTCIV AS EC
    ON PE.SK_ESTCIV = EC.SK_ESTCIV
  JOIN DWCD_ESCOLARIDADE AS EL
    ON PE.SK_ESCOLARIDADE = EL.SK_ESCOLARIDADE
"""

df_pessoa = pd.read_sql_query(query, conn_dw)
conn_dw.close()

df_pessoa

"""# Criando DIME_PESSOA"""

cur_dm.execute("""DROP TABLE IF EXISTS DIME_PESSOA;""")

cur_dm.execute("""
CREATE TABLE DIME_PESSOA (
    SK_PESSOA INTEGER PRIMARY KEY,
    CD_SEXO INTEGER NOT NULL,
    DS_SEXO TEXT NOT NULL,
    CD_RACA INTEGER NOT NULL,
    DS_RACA TEXT NOT NULL,
    CD_ESTCIV INTEGER NOT NULL,
    DS_ESTCIV TEXT NOT NULL,
    CD_ESCOLARIDADE INTEGER NOT NULL,
    DS_ESCOLARIDADE TEXT NOT NULL,
    IDADE INTEGER NOT NULL,
    FAIXA_ETARIA TEXT NOT NULL,
    DT_CARGA DATE NOT NULL DEFAULT CURRENT_DATE
);
""")

df_pessoa.to_sql('DIME_PESSOA', conn_dm, if_exists='append', index=False)

conn_dm.commit()
conn_dm.close()