# -*- coding: utf-8 -*-
"""DIME_ASSISTMED.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mgcgQtJLoCr5hcAglJ0OmxjtJnvNbK5g
"""

import sqlite3
import pandas as pd

URL = "/content/drive/MyDrive/Projeto_Final_BI/"
URL_STORE = URL+"DM/"

from google.colab import drive
drive.mount('/content/drive')

conn_extract = sqlite3.connect(URL+"DW/dw_mortalidade.db")
conn_store = sqlite3.connect(URL_STORE+"dm_mortalidade.db")

cur_extract = conn_extract.cursor()
cur_store = conn_store.cursor()

query = "SELECT * FROM DWCD_ASSISTMED"
df_am = pd.read_sql_query(query, conn_extract)

df_am.drop("DT_CARGA", inplace=True, axis=1)

conn_store.execute("""

DROP TABLE IF EXISTS DIME_ASSISTMED;

""")

conn_store.execute("""
CREATE TABLE DIME_ASSISTMED (
    SK_ASSISTMED INTEGER PRIMARY KEY,
    CD_ASSISTMED INTEGER NOT NULL,
    DS_ASSISTMED TEXT NOT NULL,
    DT_CARGA DATE DEFAULT CURRENT_DATE
    );
""")

df_am.to_sql("DIME_ASSISTMED", conn_store, if_exists="append", index=False)

conn_extract.close()
conn_store.commit()
conn_store.close()

