# -*- coding: utf-8 -*-
"""DIME LOCALIDADE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15O-RCywTtXBQqALytQbqNea958SCLlyR

# Imports e conexões
"""

import sqlite3
import pandas as pd

URL = "/content/drive/MyDrive/Projeto_Final_BI/"
URL_STORE = URL+"DM/"

conn_dw = sqlite3.connect(URL+"dw_mortalidade.db")
conn_dm = sqlite3.connect(URL_STORE+"dm_mortalidade.db")

cur_dw = conn_dw.cursor()
cur_dm = conn_dm.cursor()

"""# Extraindo dados do DW"""

query = """
  SELECT
    MU.SK_MUNICIPIO,
    MU.CD_MUNICIPIO,
    MU.NM_MUNICIPIO,
    MU.NM_MICRORREGIAO,
    UF.CD_UF,
    UF.SG_UF,
    UF.NM_UF
  FROM DWCD_MUNICIPIO AS MU
  JOIN DWCD_UF AS UF
    ON MU.SK_UF = UF.SK_UF
"""

df_localidade = pd.read_sql_query(query, conn_dw)
conn_dw.close()

df_localidade.rename(columns={
    'SK_MUNICIPIO': 'SK_LOCALIDADE'
}, inplace=True)

"""# Criando DIME_LOCALIDADE"""

cur_dm.execute("""DROP TABLE IF EXISTS DIME_LOCALIDADE;""")

cur_dm.execute("""
CREATE TABLE DIME_LOCALIDADE (
    SK_LOCALIDADE INTEGER PRIMARY KEY,
    CD_MUNICIPIO INTEGER NOT NULL,
    NM_MUNICIPIO TEXT NOT NULL,
    NM_MICRORREGIAO INTEGER NOT NULL,
    CD_UF TEXT NOT NULL,
    SG_UF INTEGER NOT NULL,
    NM_UF TEXT NOT NULL
);
""")

df_localidade.to_sql('DIME_LOCALIDADE', conn_dm, if_exists='append', index=False)

conn_dm.commit()
conn_dm.close()