# -*- coding: utf-8 -*-
"""DIME_TEMPO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xYl-ZKRL4NiyW1WxG-miwgpNKYUggtoS
"""

import sqlite3
import pandas as pd

URL = "/content/drive/MyDrive/Projeto_Final_BI/"
URL_STORE = URL+"DM/"

from google.colab import drive
drive.mount('/content/drive')

conn_extract = sqlite3.connect(URL+"DW/dw_mortalidade.db")
conn_store = sqlite3.connect(URL_STORE+"dm_mortalidade.db")

cur_extract = conn_extract.cursor()
cur_store = conn_store.cursor()

query = """
  SELECT DISTINCT(DT_OBITO)
  FROM DWMV_OBITO;
"""

df_time = pd.read_sql_query(query, conn_extract)

"""## Dicionários de nome"""

dict_semestre = {1: "1º Semestre", 2: "2º Semestre"}

dict_trimestre = {1: "1º Trimestre", 2: "2º Trimestre", 3: "3º Trimestre", 4: "4º Trimestre"}

dict_meses = {
    1: 'Janeiro',
    2: 'Fevereiro',
    3: 'Março',
    4: 'Abril',
    5: 'Maio',
    6: 'Junho',
    7: 'Julho',
    8: 'Agosto',
    9: 'Setembro',
    10: 'Outubro',
    11: 'Novembro',
    12: 'Dezembro'
}

"""## Tratamento data"""

df_time["DT_OBITO"] = pd.to_datetime(df_time["DT_OBITO"])

df_time["DT_OBITO_STR"] = df_time["DT_OBITO"].astype("str")

df_time["DT_ANO"] = df_time["DT_OBITO"].dt.year
df_time["DT_MES"] = df_time["DT_OBITO"].dt.month
df_time["DT_SEMESTRE"] = ((df_time["DT_MES"] - 1) // 6) + 1
df_time["DT_TRIMESTRE"] = ((df_time["DT_MES"] - 1) // 3) + 1
df_time["DT_ANOMES"] = df_time["DT_OBITO"].dt.strftime("%Y-%m")
df_time["SK_TEMPO"] = df_time["DT_OBITO"].dt.strftime("%Y%m")

#TODO: NM_SEMESTRE
df_time["NM_SEMESTRE"] = df_time["DT_SEMESTRE"].map(dict_semestre)
#TODO: NM_TRIMESTRE
df_time["NM_TRIMESTRE"] = df_time["DT_TRIMESTRE"].map(dict_trimestre)
#TODO: NM_MES
df_time["NM_MES"] = df_time["DT_MES"].map(dict_meses)

df_time.columns

df_time = df_time[['SK_TEMPO', 'DT_ANO', 'DT_ANOMES', 'DT_SEMESTRE', 'NM_SEMESTRE',
       'DT_TRIMESTRE',  'NM_TRIMESTRE', 'DT_MES',
       'NM_MES']]

df_time.drop_duplicates("SK_TEMPO", inplace=True)

df_time

conn_store.execute("""

DROP TABLE IF EXISTS DIME_TEMPO;

""")

conn_store.execute("""
CREATE TABLE DIME_TEMPO (
    SK_TEMPO INTEGER PRIMARY KEY,
    DT_ANO INTEGER NOT NULL,
    DT_ANOMES TEXT NOT NULL,
    DT_SEMESTRE INTEGER NOT NULL,
    NM_SEMESTRE TEXT NOT NULL,
    DT_TRIMESTRE INTEGER NOT NULL,
    NM_TRIMESTRE TEXT NOT NULL,
    DT_MES INTEGER NOT NULL,
    NM_MES TEXT NOT NULL,
    DT_CARGA DATE DEFAULT CURRENT_TIMESTAMP
    );
""")

df_time.to_sql("DIME_TEMPO", conn_store, if_exists="append", index=False)

conn_extract.close()
conn_store.commit()
conn_store.close()

