# -*- coding: utf-8 -*-
"""FATO_OBITO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pX2gcVLZtr4lBtGsyszsW6BMr9-mkkHH

# Imports e conexões
"""

import sqlite3
import pandas as pd
from datetime import datetime

URL = "/content/drive/MyDrive/Projeto_Final_BI/"
URL_STORE = URL+"DM/"

conn_extract = sqlite3.connect(URL+"DW/dw_mortalidade.db")
conn_store = sqlite3.connect(URL_STORE+"dm_mortalidade.db")

cur_store = conn_store.cursor()

"""# Extraindo e tratando dados do DW"""

query = """
    SELECT
      SK_PESSOA,
      SK_CAUSAOBITO,
      SK_MUNICIPIO,
      SK_ASSISTMED,
      SK_GESTACIONAL,
      DT_OBITO
    FROM DWMV_OBITOS
"""

df_obito = pd.read_sql(query, conn_extract)
df_obito.head()

df_obito

df_obito['DT_OBITO'] = pd.to_datetime(df_obito['DT_OBITO'])
df_obito["SK_TEMPO"] = df_obito["DT_OBITO"].dt.strftime("%Y%m")

df_obito['QT_OBITO'] = 1

df_obito.rename(columns={'SK_MUNICIPIO': 'SK_LOCALIDADE'}, inplace=True)

df_obito

df_obito = df_obito.groupby(['SK_PESSOA', 'SK_CAUSAOBITO', 'SK_LOCALIDADE', 'SK_ASSISTMED', 'SK_TEMPO', 'SK_GESTACIONAL'], as_index=False).agg(
    QT_OBITO = ('QT_OBITO', 'sum')
)

df_obito = df_obito[['SK_PESSOA', 'SK_CAUSAOBITO', 'SK_LOCALIDADE', 'SK_ASSISTMED', 'SK_TEMPO', 'SK_GESTACIONAL', 'QT_OBITO']]

df_obito

"""# Criando e Inserindo dados na FATO_OBITO"""

cur_store.execute("""DROP TABLE IF EXISTS FATO_OBITO;""")

cur_store.execute("""
CREATE TABLE FATO_OBITO (
    SK_PESSOA INTEGER,
    SK_CAUSAOBITO INTEGER,
    SK_LOCALIDADE INTEGER,
    SK_ASSISTMED INTEGER,
    SK_TEMPO INTEGER,
    SK_GESTACIONAL INTEGER,
    QT_OBITO INTEGER NOT NULL,
    DT_CARGA DATE NOT NULL DEFAULT CURRENT_DATE,
    PRIMARY KEY (SK_PESSOA, SK_CAUSAOBITO, SK_LOCALIDADE, SK_ASSISTMED, SK_TEMPO, SK_GESTACIONAL)
);
""")

df_obito.to_sql('FATO_OBITO', conn_store, if_exists='append', index=False)

conn_extract.close()
conn_store.commit()
conn_store.close()