# -*- coding: utf-8 -*-
"""DWCD_SEXO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kgktr9ozhTLnspiwotIEHEFp2e8dOtWx
"""

import pandas as pd
import sqlite3
from datetime import datetime

from google.colab import drive
drive.mount('/content/drive')

URL = "/content/drive/MyDrive/Projeto_Final_BI/DW/"

conn = sqlite3.connect(URL+"dw_mortalidade.db")

cur = conn.cursor()

dict_sex = {
    0 : "Ignorado",
    2 : "Feminino",
    1 : "Masculino",
}

sks = len(dict_sex.items())
df = pd.DataFrame(range(1, sks+1), columns=["SK_SEXO"])

df["CD_SEXO"] = dict_sex.keys()
df["DS_SEXO"] = dict_sex.values()

df["DT_CARGA"] = datetime.now().date()

cur.execute("""

DROP TABLE IF EXISTS DWCD_SEXO;

""")

cur.execute("""
CREATE TABLE DWCD_SEXO (
    SK_SEXO INTEGER PRIMARY KEY,
    CD_SEXO INTEGER NOT NULL,
    DS_SEXO TEXT,
    DT_CARGA DATE
    );
""")

df.to_sql("DWCD_SEXO", conn, if_exists="append", index=False)

conn.commit()

conn.close()