# -*- coding: utf-8 -*-
"""ETL_DWCD_CIRCOBITO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e2NCXkJNahoUf_ftpjchSynNy0lgPkJF
"""

import pandas as pd
from datetime import datetime
import sqlite3

URL = "/content/drive/MyDrive/Projeto_Final_BI/DW/"

dict_circobito = {
    -1 : "Não se aplica",
    1 : "Acidente",
    2 : "Suicídio",
    3 : "Homicídio",
    4 : "Outros",
    9 : "Ignorado",
}

sks = len(dict_circobito.items())
sk_values = [-1] + list(range(1, sks))
df = pd.DataFrame(sk_values, columns=["SK_CIRCOBITO"])

df["CD_CIRCOBITO"] = dict_circobito.keys()
df["DS_CIRCOBITO"] = dict_circobito.values()

df["DT_CARGA"] = datetime.now().date()
df

conn = sqlite3.connect(URL+"dw_mortalidade.db")
cur = conn.cursor()

cur.execute("""DROP TABLE IF EXISTS DWCD_CIRCOBITO;""")

cur.execute("""
CREATE TABLE DWCD_CIRCOBITO (
    SK_CIRCOBITO INTEGER PRIMARY KEY,
    CD_CIRCOBITO INTEGER NOT NULL,
    DS_CIRCOBITO TEXT,
    DT_CARGA DATE
    );
""")


df.to_sql("DWCD_CIRCOBITO", conn, if_exists="append", index=False)
conn.commit()
conn.close()