# -*- coding: utf-8 -*-
"""ETL DWCD_MUNICIPIO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dWov9GQCkmS8E-yv5nF_RA3is8midmCL
"""

import pandas as pd
from datetime import datetime
import sqlite3

URL = "/content/drive/MyDrive/Projeto_Final_BI/"
URL_DW = URL + "DW/dw_mortalidade.db"

conn = sqlite3.connect(URL_DW)
cur = conn.cursor()

cur.execute("""
CREATE TABLE IF NOT EXISTS DWCD_MUNICIPIO (
    SK_UF INTEGER NOT NULL,
    SK_MUNICIPIO INTEGER PRIMARY KEY,
    CD_MUNICIPIO INTEGER NOT NULL,
    NM_MUNICIPIO TEXT NOT NULL,
    NM_MICRORREGIAO TEXT NOT NULL,
    DT_CARGA DATE NOT NULL
);
""")

# Cria index para não permitir dados duplicados
cur.execute("""
CREATE UNIQUE INDEX IF NOT EXISTS idx_m_unico
ON DWCD_MUNICIPIO (SK_UF, CD_MUNICIPIO);
""")

conn.commit()
conn.close()

# Conecta ao DW
conn_dw = sqlite3.connect(URL_DW)
cur = conn_dw.cursor()

# Anexa o banco de staging
cur.execute(f"ATTACH DATABASE '{URL}STG/staging.db' AS stg;")

# Cria a tabela temporária
cur.execute("""
CREATE TEMP TABLE temp_cte_mu AS
SELECT DISTINCT M.CD_MUNICIPIO, M.NM_MUNICIPIO, M.NM_MICRORREGIAO, U.SK_UF
FROM stg.STG_LOCALIDADE M
JOIN DWCD_UF U ON M.CD_UF = U.CD_UF;
""")

# Atualiza registros existentes
cur.execute("""
UPDATE DWCD_MUNICIPIO
SET
    NM_MUNICIPIO = (SELECT NM_MUNICIPIO FROM temp_cte_mu c WHERE c.CD_MUNICIPIO = DWCD_MUNICIPIO.CD_MUNICIPIO AND c.SK_UF = DWCD_MUNICIPIO.SK_UF),
    NM_MICRORREGIAO = (SELECT NM_MICRORREGIAO FROM temp_cte_mu c WHERE c.CD_MUNICIPIO = DWCD_MUNICIPIO.CD_MUNICIPIO AND c.SK_UF = DWCD_MUNICIPIO.SK_UF),
    DT_CARGA = CURRENT_DATE
WHERE EXISTS (SELECT 1 FROM temp_cte_mu c WHERE c.CD_MUNICIPIO = DWCD_MUNICIPIO.CD_MUNICIPIO AND c.SK_UF = DWCD_MUNICIPIO.SK_UF);
""")

# Insere novos dados
cur.execute("""
INSERT OR IGNORE INTO DWCD_MUNICIPIO (CD_MUNICIPIO, NM_MUNICIPIO, NM_MICRORREGIAO, SK_UF, DT_CARGA)
SELECT CD_MUNICIPIO, NM_MUNICIPIO, NM_MICRORREGIAO, SK_UF, CURRENT_DATE
FROM temp_cte_mu;
""")

cur.execute("""
INSERT OR IGNORE INTO DWCD_MUNICIPIO (SK_UF, SK_MUNICIPIO, CD_MUNICIPIO, NM_MUNICIPIO, NM_MICRORREGIAO, DT_CARGA)
SELECT -1, -1, -1, 'Desconhecido', 'Desconhecido', CURRENT_DATE
WHERE NOT EXISTS (SELECT 1 FROM DWCD_MUNICIPIO WHERE SK_MUNICIPIO = -1);
""")

conn_dw.commit()
conn_dw.close()