# -*- coding: utf-8 -*-
"""ETL_DWCD_RACA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dAVeepIIIfcp948MVXV1OG0rxEPtSLn1
"""

import pandas as pd
from datetime import datetime
import sqlite3

URL = "/content/drive/MyDrive/Projeto_Final_BI/DW/"

from google.colab import drive
drive.mount('/content/drive')

dict_raca = {
    -1 : "Ignorado",
    1 : "Branca",
    2 : "Preta",
    3 : "Amarela",
    4 : "Parda",
    5 : "Indígena",
}

sks = len(dict_raca.items())
sk_values = [-1] + list(range(1, sks))
df = pd.DataFrame(sk_values, columns=["SK_RACA"])

df["CD_RACA"] = dict_raca.keys()
df["DS_RACA"] = dict_raca.values()

df["DT_CARGA"] = datetime.now().date()

conn = sqlite3.connect(URL+"dw_mortalidade.db")
cur = conn.cursor()

cur.execute("""DROP TABLE IF EXISTS DWCD_RACA;""")

cur.execute("""
CREATE TABLE IF NOT EXISTS DWCD_RACA (
    SK_RACA INTEGER PRIMARY KEY,
    CD_RACA INTEGER NOT NULL,
    DS_RACA TEXT,
    DT_CARGA DATE
    );
""")


df.to_sql("DWCD_RACA", conn, if_exists="append", index=False)
conn.commit()
conn.close()