# -*- coding: utf-8 -*-
"""ETL_DWCD_ESCOLARIDADE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-wVNZ1-m3DhXX6gM31S2XIPax8tR0id4
"""

import pandas as pd
from datetime import datetime
import sqlite3

URL = "/content/drive/MyDrive/Projeto_Final_BI/DW/"

from google.colab import drive
drive.mount('/content/drive')

dict_escolaridade = {
    -1 : "Não Identificado",
    0 : "Sem Escolaridade",
    1 : "Fundamental I",
    2 : "Fundamental II",
    3 : "Médio",
    4 : "Superior Incompleto",
    5 : "Superior Completo",
    9 : "Ignorado"
}

sks = len(dict_escolaridade.items())
sk_values = [-1] + list(range(1, sks))
df = pd.DataFrame(sk_values, columns=["SK_ESCOLARIDADE"])

df["CD_ESCOLARIDADE"] = dict_escolaridade.keys()
df["DS_ESCOLARIDADE"] = dict_escolaridade.values()

df["DT_CARGA"] = datetime.now().date()

conn = sqlite3.connect(URL+"dw_mortalidade.db")
cur = conn.cursor()

cur.execute("""DROP TABLE IF EXISTS DWCD_ESCOLARIDADE;""")

cur.execute("""
CREATE TABLE IF NOT EXISTS DWCD_ESCOLARIDADE (
    SK_ESCOLARIDADE INTEGER PRIMARY KEY,
    CD_ESCOLARIDADE INTEGER NOT NULL,
    DS_ESCOLARIDADE TEXT,
    DT_CARGA DATE
    );
""")

conn = sqlite3.connect(URL+"dw_mortalidade.db")
df.to_sql("DWCD_ESCOLARIDADE", conn, if_exists="append", index=False)

conn.commit()
conn.close()